fix typo in method name getRequesteApiVersion()
SLF4JServiceProvider defines the `getRequestedApiVersion()` method, but this class has a typo, the method is incorrectly named `getRequesteApiVersion()` which causes the following error message to be reported when using this library:

```
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
```