[LOG4J2-3624] Protects `ServiceLoaderUtil` from unchecked exception
Contrary to the documentation `ServiceLoader` can also throw unchecked
exceptions such as `NoClassDefFoundError` or other `LinkageError`s. This
should not prevent `ServiceLoaderUtil` from returning those services,
which are not broken.

This PR logs all exceptions, but rethrows everything exception
`LinkageError` and `ServiceConfigurationError`: users expect exceptions
such as `SecurityException` to break Log4j2 API until an administrator
fixes them.